[package]
name = "yum-commits"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
ollama-rs = "0.2.1"
tokio = { version = "1.40.0", features = ["full"] }
